### ISSUE TITLE
Replace StringTokenizer

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#163]
See https://github.com/JabRef/jabref/issues/1877 and the link in the comment http://stackoverflow.com/questions/691184/scanner-vs-stringtokenizer-vs-string-split

**Comment by Siedlerchr** [comment]
I just learned the Regex/Matcher Split can also be used in combination with streams:
http://winterbe.com/posts/2015/03/25/java8-examples-string-number-math-files/

**Comment by koppor** [comment]
One can search for `StringTokenizer` using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd>.

**Comment by PFvanBeerendonk** [comment]
Would like to take this issue.

**Comment by koppor** [comment]
Assigned!

As a general advice for newcomers: check out [Contributing](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md) for a start. Also, [guidelines for setting up a local workspace](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace) is worth having a look at.

Feel free to ask here at GitHub, if you have any issue related questions. If you have questions about how to setup your workspace use JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat. Try to open a (draft) pull-request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.

**Comment by PFvanBeerendonk** [comment]
I have some minor questions.

1. I am considering not replacing QuotedStringTokenizer since it is its own class, and does not use deprecated class StringTokenizer.
2. All changes are internal, and all internal parts should already be tested. So I assume I do not need to add test cases (since I'm not adding or changing functionality?)

**Comment by PFvanBeerendonk** [comment]
PR is ready

**Comment by koppor** [comment]
Thank you for investigating this. Comments on the PR.
