### ISSUE TITLE
JabRef reformats complete file on load

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#251]
I collaboratively work on a paper and jabref reformats the whole bib file on load (and shows a star). How can this happen? Although I like this feature, I cannot find how to active/deactivte it

![reformat-all gif](https://user-images.githubusercontent.com/1366654/29627781-87df6ac0-8833-11e7-8b85-0aab2828411f.gif)

![grafik](https://user-images.githubusercontent.com/1366654/29627548-b4722cd6-8832-11e7-96f9-31fea8a8a0b3.png)

**Comment by lenhard** [comment]
Just a wild guess, but I've had similar problems when entering field content that lead to an immediate reformatting of the field (which is fixed now).

The problem was that an EntryChangeEvent triggers the BackupManager and the BackupManager triggers the save actions that are configured. I guess it's the same for you here. So the solution should be:
 - Don't trigger save actions with the BackupManager does a backup (not sure if easily possible)
 - Find out why there's a change event fired when you just open the entry editor

**Comment by koppor** [comment]
I think, there is no entry editor opened. At least, I don't see it initially.

**Comment by lenhard** [comment]
You are right. The database is immediately marked as dirty. But the change only happens when you click on an entry. This opens the entry preview and not the entry editor (my bad). One of these things (entry selection or opening entry preview) seems to trigger the event.

**Comment by koppor** [comment]
Yes, it are the listeners. `git bisect` lead me to 59b979484828b72536400b4be7f9234c0ab03d4b - introduced in https://github.com/JabRef/jabref/pull/3001.

**Comment by lenhard** [comment]
We should find out why already opening a database triggers a `BibDatabaseContextChangedEvent` (which is what the listeners react to). This is after all what the `BasePanel` reacts to.

**Comment by koppor** [comment]
So, my next `git bisect` guess is edd3f7cc1395ec197e329629550cef52b953f7f7 coming from https://github.com/JabRef/jabref/pull/2971. Checked it twice here.

**Comment by tobiasdiez** [comment]
@koppor try to set a breakpoint in the file writing class and then just look at the stack trace to see what event triggers the save.

**Comment by koppor** [comment]
It is somehow an interplay between save actions and some changes we did. - I cannot manually save the database, because this triggers the save actions and leads to a change of the file.

So, this is not a bug, it is a feature.
