### ISSUE TITLE
Group interface: Usability

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#277]
- [ ] double click on a group should open edit mode
- [ ] When pressing `+`, the dialog should show "Add group" not "Edit group properties"

![grafik](https://user-images.githubusercontent.com/1366654/34289841-ac3a8c22-e6f4-11e7-9478-2ab18282061b.png)

**Comment by tobiasdiez** [comment]
@koppor I just stumbled upon a problem which resulted from the "double click = show edit dialog" change. Previously, it is was possible to expand/collapse groups by double clicking which now longer works since the edit dialog also pops up. I find both behaviors kind of natural but suspect that you expand/collapse more often than edit and would thus vote to revert https://github.com/JabRef/jabref/pull/3715.

**Comment by koppor** [comment]
I would not completely revert the commit, because label of the dialog should be kept.

I am not working with group trees, but with flat groups, where the double click did nothing. For me, it is OK to revert that behavior.
