### ISSUE TITLE
Serialization changed

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#34]
The recent master branch changes the order of fields. Is it possible to keep the order of the fields as they were in the version of october? I have not changed my preferences, it is still `Save fields sorted in alphabetic order (as in versions 2.10+)`. @stefan-kolb maybe?

![grabbed_20151120-183827](https://cloud.githubusercontent.com/assets/1366654/11307039/e6b0b5fe-8fb5-11e5-8480-9f423d77f079.png)

![grabbed_20151120-183849](https://cloud.githubusercontent.com/assets/1366654/11307050/f373e20c-8fb5-11e5-8576-bddf3ed4e4ae.png)

![grabbed_20151120-183800](https://cloud.githubusercontent.com/assets/1366654/11307027/d69de934-8fb5-11e5-837e-a36318daec8d.png)

**Comment by koppor** [comment]
Well, maybe some fields moved from "required" to "optional". But Why is "Journal" getting optional in `@Article`? - Maybe the old ordering was wrong. I Wonder why "Year" was written before "Editor" in my `@Inproceedings`.

![grabbed_20151123-015254](https://cloud.githubusercontent.com/assets/1366654/11328147/ec9e8038-9184-11e5-8b32-f7294d02e965.png)

![grabbed_20151123-015305](https://cloud.githubusercontent.com/assets/1366654/11328150/f25d65d4-9184-11e5-82ad-5fbaf4f7092d.png)

**Comment by lenhard** [comment]
No, it is not possible to leave the order of fields as it was in October, since we decided during the last dev call to change it to the ordering stated in the Bibtex manual.

But as far as I know, no one deliberately changed field order and the one above also does not make sense, so this is a bug. Serialization depends on the order in which fields are stated, so the changes made here https://github.com/JabRef/jabref/pull/352 are probably the cause. But at the moment I don't understand how.

**Comment by koppor** [comment]
Ordering: Yes. But I would have expected that to happen only if I write new entries and the old ones should remain untouched. This eases parallel usage of JabRef 2.10, 2.11., and 3.0.

We sort the req and opt fields when writing. Maybe there something goes wrong, because we return umodifiable lists now at the types.

**Comment by lenhard** [comment]
That is true. But not modifiying existing entries is a mountain of work to implement, so I guess that no one will touch that for a very long time, if ever.

Regarding the unmodifiable lists: That change is ages old. Thus it is highly unlikely that it is the cause. I would rather guess that a resorting of the fields in the collections (when creating the types) is the reason.

**Comment by stefan-kolb** [comment]
Looks like this is caused by the method `getRequiredFields()`. `getRequiredFields()` returns required fields including alternatives, e.g. `author/editor`. This is why it might be serialzed last. The new method `getRequiredFieldsFlat()` now returns all fields without alternative syntax. I thought this was replaced correctly everywhere, but we might have to keep an eye on this!

**Comment by stefan-kolb** [comment]
https://github.com/JabRef/jabref/commit/db15dc23f7e4456e092c8c323b31a3745b148d13

**Comment by koppor** [comment]
Works for me :+1:

**Comment by koppor** [comment]
@stefan-kolb Could you fix that for biblatex mode, too?

**Comment by stefan-kolb** [comment]
Is this an issue? Biblatex entries should be written like Bibtex entries, therefore this should already work as expected.

**Comment by koppor** [comment]
Think, I used a wrong jar, even if I double checked. On my second machine (Win 8.1), it works perfectly (besides the changed serialization). Java `1.8.0_66`. Will recheck the next days on my primary machine.
