### ISSUE TITLE
Be more relaxed when handling file paths

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#52]
Our main user base seems to use Windows. These users are not used to escape path separators. E.g., they use `C:\xxxx\yyyy\zzzz\somefilename.pdf`. Instead of throwing exceptions etc., JabRef should be able to treat such path specifications. Possibly, if on Windows, replace `\` followed by a non-`\` by `\\` before letting the String really be handled by Java.

Refs https://github.com/JabRef/jabref/issues/184#issuecomment-159187452 and #98

**Comment by matthiasgeiger** [comment]
Those paths are escaped by JabRef (and even Zotero) by default - however, JabRef 2.11 GUI currently breaks completely if (somehow) an unescaped path is stored in the file. In 3.0dev the UI is not affected, but the file field does not contain sensible information due to the unescaped delimiter ":" in `C:\...`

**Comment by simonharrer** [comment]
This requires too much strange logic to support.

**Comment by ror3d** [comment]
I would suggest to normalize paths to unix-style instead. Windows supports it, and it would make files work well between systems.

**Comment by koppor** [comment]
Follow-up at https://github.com/JabRef/jabref/issues/10871
