### ISSUE TITLE
Button to create a group should be in the header

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#529]
There is much empty space in the header of the groups. Can we add the "New group" button in that pane?

![image](https://user-images.githubusercontent.com/1366654/139821903-55d87f15-1ec9-431f-8503-72a3e3434816.png)

**Comment by DavidOWade** [comment]
Can I work on this issue?

**Comment by ThiloteE** [comment]
This issue here is just one of multiple competing alternatives to fix https://github.com/JabRef/jabref/issues/8398.
@DavidOWade sorry I am not actively monitoring Koppor/JabRef and looks like Koppor failed to make this clear. This issue here is an older proposal and may be outdated.

There was a lengthy discussion in https://github.com/JabRef/jabref/pull/8462 with devcall and https://github.com/JabRef/jabref/pull/8462#issuecomment-1063485676 was the proposed way forward.
