### ISSUE TITLE
Message after import should be passive

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#548]
![grafik](https://user-images.githubusercontent.com/1366654/147218805-d5a378b9-33a1-4ee9-a7d3-da33eb20160c.png)

The message should contain "created new entry" or "merged into existing entry"

**Comment by Racheal7** [comment]
Hi Oliver, can I take this issue? I am a student at the Australian National University and would like to contribute to the JabRef repo as part of my assignment. 

Thank you~

**Comment by Racheal7** [comment]
@ThiloteE Hi there, thank you for assigning me. 

Just want to clarify, my solution for the issue can be found in the [Pull Requeset](https://github.com/Racheal7/jabref/pull/3). However, as my team member pointed out, the messages are more like "past tense" rather than "passive". Is that okay or should I change the messages to passive tense such as "A new file was imported"?

In addition, the icon after successfully importing a BibTex is currently the "warning" icon, which I assume is a bug and it should be the "check" icon. I have already modified it in my PR but just want to confirm with you. 

Thank you very much!

**Comment by ThiloteE** [comment]
Both Oliver Kopp and me are not native Speakers of the English language. Now that I think about it, yes a "passive" form of the past might be preferable. To be honest, since you study in Australia, which is an English Speaking Country, I think you might have a better feeling for what is right or wrong here. Whatever you choose, it will definitely be an improvement to the status quo.

**Comment by koppor** [comment]
@Racheal7 Thank you for working on this. -- A discussion of the solution should be done at the solution and not at the issue. Let's discuss at the pull request.

**Comment by koppor** [comment]
Everything was settled down at https://github.com/JabRef/jabref/pull/9308 - no discussion needed any more.

@Racheal7 Thank you for working on this!

**Comment by Racheal7** [comment]
Thank you, Oliver @koppor
