### ISSUE TITLE
Path should be relative after import at "Find Unlinked Files"

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#549]
(Update)

As user I might a directory of files, for which there is no repesentation in my local library. I can use "Search for unlinked local files"

![grafik](https://user-images.githubusercontent.com/1366654/198401464-a87bdf69-b2cd-47d0-934b-cbd83a4b41a6.png)

A documentation is available at https://docs.jabref.org/collect/findunlinkedfiles#link-the-pdfs-to-your-bib-library

When I run the tool and import entries, the full absolute path is written:

```bibtex

    file      = {:C\:/Users/koppor/git-repositories/paper/bib/pdfs/Adapting BDDs for Visualizing Product Configuration Data.pdf:PDF},
```
expected:

```
    file      = {:Adapting BDDs for Visualizing Product Configuration Data.pdf:PDF},
```

because of

```
    @Comment{jabref-meta: fileDirectory:pdfs;}
```

The `.bib` file is located in `C\:/Users/koppor/git-repositories/paper/bib`. Therefore, the configuration of the path `pdf` works.

## How to reproduce

1. Put test PDF files in `c:\jabref-test\pdfs`
2. Create `test.bib` in `c:\jabref-test`
3. Configure `c:\jabref-test\pdfs` as PDF path int he library:
  ![grafik](https://user-images.githubusercontent.com/1366654/198401999-0453e865-2458-4ce6-baff-b9a68ed23c4c.png)
4. Execute the ["Search for unlinked local files"](https://docs.jabref.org/collect/findunlinkedfiles#link-the-pdfs-to-your-bib-library)

## Implementation Hints

The functionality to call is the same as in the cleanup entries dialog

![grafik](https://user-images.githubusercontent.com/1366654/147226873-4d07bf96-1028-4ab6-aff7-2c9a0b580fab.png)

**Comment by Racheal7** [comment]
Hi Oliver, can I please take this issue? I just started to learn Java and would like to get more practical experience. Thank you~

**Comment by u7232539** [comment]
Hi there, I managed to change the path to a relative path.

I think the method `getFileDirectories` is not returning the path of the file, that's why the method `relativize` isn't working.
The fix is to add the file path, so it can be relativized.

**Before:**
The file path is an absolute path.
![image](https://user-images.githubusercontent.com/110802700/198217271-9859b2d5-64e5-4f69-a74a-6e2fb33de095.png)

**After:**
The file path is a relative path.
![image](https://user-images.githubusercontent.com/110802700/198217461-b02bd892-eba3-40d1-bc77-303831f30665.png)

But I found 2 more issues.

1. In the cleanup entries, the default of `Make paths of linked files relative (if possible)` is ticked. But it does not show the relative path by default. In order to show the relative path, users need to press the OK button in the cleanup entries.

2. Relative path cannot revert back to the absolute path. After unchecking the checkbox  `Make paths of linked files relative (if possible)` , the path is still a relative path.

**Comment by koppor** [comment]
> Hi there, I managed to change the path to a relative path.

Just as a double check: Did you really use the funtionality "Search for unlinked files"

![grafik](https://user-images.githubusercontent.com/1366654/198401315-577d6dc8-ca13-48bd-8d83-bc2230e3a722.png)

I refined the issue description accordingly. - I am sorry if it was non-understandable before (therefore, I also put the label "issue-understanding")

> I think the method `getFileDirectories` is not returning the path of the file, that's why the method `relativize` isn't working. The fix is to add the file path, so it can be relativized.

What did you configure as PDF directory in your .bib file? I put the section "How to reproduce" above to show exact steps.

> 
> **Before:** The file path is an absolute path. ![image](https://user-images.githubusercontent.com/110802700/198217271-9859b2d5-64e5-4f69-a74a-6e2fb33de095.png)
> 
> **After:** The file path is a relative path. ![image](https://user-images.githubusercontent.com/110802700/198217461-b02bd892-eba3-40d1-bc77-303831f30665.png)

> Also, I found 2 more issues.
> 
>     1. In the cleanup entries, the default of `Make paths of linked files relative (if possible)` is ticked. But it does not show the relative path by default. 

What do you mean by "show"?

> In order to show the relative path, users need to press the OK button in the cleanup entries.

(Context: https://docs.jabref.org/finding-sorting-and-cleaning-entries/cleanupentries)

This is the intended action of the dialog. As first action, you could rename "OK" to "Apply". This should be more intuitive.

It would be great if the cleanup dialog could have a "preview" of the things to be done. However, I think, this is difficult, because all actions need to be reverted when pressing "Cancel".

>     2. Relative path cannot revert back to the absolute path. After unchecking the checkbox  `Make paths of linked files relative (if possible)` , the path is still a relative path.

Yes, there is no cleanup action for that. This is intended as we think, relative paths are better.

**Comment by u7232539** [comment]
I am sorry that I did not understand this issue correctly and did not use the functionality "Search for unlinked files" to reproduce this issue.

Now I have configured this in my .bib file, applied "Search for unlinked files" and imported 1 pdf file. from C\:/Downloads/ 
![image](https://user-images.githubusercontent.com/110802700/198504895-79a598d5-fc4b-4efc-8e26-47ded9e62271.png)

**This is what I got after the import at "Find Unlinked files".**
`file     = {:C\:/Downloads/started2021 - V.pdf:PDF}`

One thing I am not sure about is the location of the file. Should it be its original location (C\:/Downloads/...) or under the `C:\jabref_test\pdfs`?


> This is the intended action of the dialog. As first action, you could rename "OK" to "Apply". This should be more intuitive.
It would be great if the cleanup dialog could have a "preview" of the things to be done. However, I think, this is difficult, because all actions need to be reverted when pressing "Cancel".

Yes, you are right.

>Yes, there is no cleanup action for that. This is intended as we think, relative paths are better.

Then perhaps users should be alerted that this is an irreversible action?

**Comment by koppor** [comment]
In your example, the path CANNOT be relativzed, because JabRef only uses the sub directory of the path in "General file directory"

The paths marked in yellow are neither the same nor is the downloads directory a sub path of the general file directory.

![grafik](https://user-images.githubusercontent.com/1366654/198741231-473f75e6-e942-4831-a2d2-9da7475443f5.png)

Thus, you can try to configure "C:\Downloads" as General file directory adn then re-run your experiment.

**Comment by IceMajor2** [comment]
Hello. Could I get assigned to work on this issue?

**Comment by u7676493** [comment]
Hello, I am here to do a university assignment where I update open source projects! I would like to work on this issue, and am wondering if it is still available to do.

**Comment by koppor** [comment]
@u7676493 Sure! Go ahead. Sorry for the delay.

**Comment by koppor** [comment]
Welcome to the vibrant world of open-source development with JabRef!

Newcomers, we're excited to have you on board. Start by exploring our [Contributing](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md) guidelines, and don't forget to check out our [workspace setup guidelines](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace) to get started smoothly.

In case you encounter failing tests during development, please check our [developer FAQs](https://devdocs.jabref.org/code-howtos/faq.html)!

Having any questions or issues? Feel free to ask here on GitHub. Need help setting up your local workspace? Join the conversation on [JabRef's Gitter chat](https://gitter.im/JabRef/jabref). And don't hesitate to open a (draft) pull request early on to show the direction it is heading towards. This way, you will receive valuable feedback.

Happy coding! 🚀

**Comment by koppor** [comment]
Closed via https://github.com/JabRef/jabref/pull/12088
