### ISSUE TITLE
Consistent spelling of "BibTeX" and "BibLaTeX"

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#73]
When seeing https://github.com/JabRef/jabref/pull/422#discussion-diff-46247118, I think, we should have a consistency check going through our web page and our code to ensure that always `` JabRef`, `BibTeX`, and `BibLaTeX` is used and not `bibtex`, `bibTeX`, `BibTex`, ...

Refs https://github.com/JabRef/jabref/issues/436

**Comment by matthiasgeiger** [comment]
:+1: 

But what is the correct spelling of "Biblatex"? ;-) The manual itself uses "Biblatex" - the ctan description uses "BibLaTeX"...

**Comment by mlep** [comment]
I think there is a convention to have package names in lower case (probably because some weird OS do not really differentiate upper and lower case... ;-) )
In its description of the package biblatex (all in lower case because it is a package name), the CTAN uses "BibTeX" and "BibLaTeX" (http://ctan.org/pkg/biblatex ). So, I guess "BibLaTeX" is good.

Phylogenic-wise, at first, there was TeX. Then came LaTeX and BibTeX.
So, it seems consistent to write BibLaTeX.

**Comment by tobiasdiez** [comment]
:+1: for BibLaTeX

**Comment by simonharrer** [comment]
:+1: for BibLaTeX as well.

**Comment by simonharrer** [comment]
I think is already implemented

**Comment by koppor** [comment]
@josephwright demands `biblatex`.

**Comment by josephwright** [comment]
I think 'demand' is a bit strong :) The original author of `biblatex`, Philip Lehmann, always spelled it all-lowercase and I (as part of the current team) have tried to stick to his approach.

**Comment by koppor** [comment]
@josephwright Is there an update on this "policy"? On CTAN, I see "BibLaTeX" --> https://ctan.org/pkg/biblatex
