### ISSUE TITLE
"Upgrade file" warning

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#98]
I upgraded from the development version as of 2015-12-05 to `2015-12-07--master--2644b6`. Now, the "Upgrade file" dialog appears. It did not appear at the old version.

![grabbed_20151207-095320](https://cloud.githubusercontent.com/assets/1366654/11622765/5bb22ff8-9cc8-11e5-8d43-34a2599bed87.png)

- [x] Need to investigate: What causes the dialog to appear now? Why did it not appear two days ago?
- [x] Rework dialog similar to the suggestion made at https://github.com/JabRef/jabref/issues/328

**Comment by lenhard** [comment]
It is highly likely that this comes from this commit bef862f6b43a74459e4c62889cc12dac3e60e780

Before the commit JabRef showed the warning if:
JabRefVersion != 2.X && SomePreferenceIsSetToTrue && ThereArePdfOrPsFieldsInTheDatabase

I removed the first part and repaired the remaining code, so it seems that there are still pdf or ps fields in your database? It is likely that the dialog did not appear previously, because the detection code was broken.

I am for just removing the dialog and upgrade...

**Comment by koppor** [comment]
Right, there are `Pdf` and `Evastar_pdf` fields in my database. I added a file with three different cases at 
https://github.com/JabRef/jabref/commit/a1ef00645a39f2d34f13f129366e1ec16abd6683. For the first entry, everything is correct. The second entry is not touched (JabRef seems to be unaware of `Evastar_pdf`). The third one contains a URL in the Pdf field, which is neither converted to the `URL` field nor downloaded and put into the `File` field.

I'd vote that JabRef makes the change transparent to the user and does not change entries behind the scenes. The text itself could be improved: It should state that fields `pdf` and `ps` are migrated into the `file` field.

**Comment by lenhard** [comment]
With 07724103ef72c42011c2038f6c8905a28648d2c1 also the `Evastar_pdf` is detected and cleaned and 14a2b3cf71d202e0d87ec7feaf1df8ef69d08cf0 improves the dialog message.

For me, the upgrade works fine for all three entries now. For the third entry, the URL is put into the pdf field and the paper can be downloaded with the help of GUI.

Please confirm that this is fixed and close.

**Comment by koppor** [comment]
On the one hand, I think: Shouldn't the URL in the PDF field be put in the field `url` instead of `file`? On the other hand, I think, I'm the only one not having understood the semantics of the `pdf` field :innocent: 

This brings me to the question: Can I store multiple URLs in the field `url`? How do I store a link to the PDF if I want to put a link to the online article and the PDF? Is this an edge case?

**Comment by lenhard** [comment]
I guess there are simply no regulations regarding the content of the `url` field, as is the case for most fields. I'm not convinced that we should change the current behavior. At least for the file field, we currently have a syntax for storing multiple entries. I you want to put a link to the online article, you can use the `url` field and for your local PDF, you can use the `pdf` field, so I don't see the problem here.

Anyways, this issue is about the appearance of the file dialog and its wording. This seems to be fixed, so this issue can be closed? If you want to change the semantics of the file upgrade functionality, this should really be a different issue.
